# Generated by Django 4.1.3 on 2022-12-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='user',
            new_name='author',
        ),
    ]
